apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dot-net-runner-deployment
  janus-idp.io/tekton: dot-net-runner-deployment
  backstage.io/kubernetes-id: dot-net-runner-deployment
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dot-net-runner-deployment
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
