apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dot-net-runner-deployment
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot-net-runner-deployment 
  name: dot-net-runner-deployment
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dot-net-runner-deployment
    weight: 100 
